-- API_COURSE_REG.COREG_SHEDLOCK definition

CREATE TABLE "COREG_SHEDLOCK"
   (	"NAME" VARCHAR2(64),
	"LOCK_UNTIL" TIMESTAMP (3),
	"LOCKED_AT" TIMESTAMP (3),
	"LOCKED_BY" VARCHAR2(255),
	 CONSTRAINT "COREG_SHEDLOCK_PK" PRIMARY KEY ("NAME")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
   TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

COMMENT ON TABLE COREG_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

GRANT SELECT ON COREG_SHEDLOCK TO GRAD_READONLY;
